### PR TITLE
😏 Fix assets path

### PR DESCRIPTION
**Pull request by PunKeel**
Always use links relative to base path.

BREAKING CHANGE: won’t work if running etu_utt in a subfolder (like
http://example.tld/web/)

Ping @tgalopin : Am I wrong on this ? (CSS is stored in /min/, images in /src/img/ ... using relative links doesn't seem to be working)

### CODE REVIEW

**Comment by tgalopin** [comment]
I check tomorrow.

**Comment by tgalopin** [comment]
I reviewed the modification and while it's correct, I think instead of this you should implement a real assets process. For instance, you could use Puli to deploy assets and Gulp to combine/compile/minify them. If you want to do that I'd be happy to give a hand to do it properly :) .

**Comment by PunKeel** [comment]
I think adding Puli and gulp makes it even harder to maintain, so we'll stick with raw paths for now (not a major change, + it's already quite hard with composer, bower+node.js ^^) 

Thanks for the feedback

**Comment by tgalopin** [comment]
It's probably true but I thought of some modifications for EtuUTT and it was one of them. At some point we should talk about the problems I  detected on EtuUTT and how I planned to fix them ;) . In the meantime

**Comment by PunKeel** [comment]
Yeah ! :)

**Pull request merged**
